name: mvpnet
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:         # everything under this, installed by conda
- python=3.6
- pip
- cudatoolkit=10.0
- future
- tensorboard
- numpy
- scipy
- scikit-learn
- h5py
- cython
- tqdm
- natsort
- tabulate
- yacs
- pytest
- opencv
- matplotlib
- plyfile
- pip:                # everything under this, installed by pip
  - open3d==0.8.0
  - wheel
  - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp37-cp37m-win_amd64.whl